---
- name: configure | Create log file
  copy:
     content=""
     dest="{{ rethinkdb_log }}"
     owner="{{ rethinkdb_user }}"
     group="{{ rethinkdb_group }}"
  when: rethinkdb_log is defined

- name: configure | Create the rethinkdb data directory
  file:
    dest={{ rethinkdb_directory }}
    mode=755
    owner={{ rethinkdb_user }}
    group={{ rethinkdb_group }}
    state=directory

- name: configure | Check if the rethinkdb data directory already exists
  stat:
    path='{{ rethinkdb_directory }}/{{ inventory_hostname }}'
  register: rethinkdb_directory_exists

- name: configure | Create the rethinkdb data
  command: rethinkdb create --runuser {{ rethinkdb_user }} --rungroup {{ rethinkdb_group }} -d {{ rethinkdb_directory }}/{{ inventory_hostname }}
  when: not rethinkdb_directory_exists.stat


- name: Create the rethinkdb config file
  template:
    src=rethinkdb.conf.j2
    dest=/etc/rethinkdb/instances.d/{{ inventory_hostname }}.conf
  notify: restart rethinkdb
